### ISSUE TITLE
Question about hyper-statusline and hyper-tabs-enhanced

### ISSUE THREAD

**Issue by henrikruscon** [alexfedoseev/hyper-hybrid-theme#1]
Been porting my color matching code from `hyper-tabs-enhanced` to `hyper-statusline` to work with a wide variety of dark/light themes and while it looks great on most themes it loses saturation with yours. Would you like me to add an option flag for saturation?

While saturation looks great with some themes it's more delicate and can look terrible depending on what foregroundColor is used so I don't want it as default ✌️

**Comment by alex35mil** [comment]
@henrikdahl Sure, I'll be happy to accept this PR 👍

**Comment by henrikruscon** [comment]
Normal behavior
![skarmavbild 2017-01-20 kl 09 44 37](https://cloud.githubusercontent.com/assets/1430576/22142071/1fe125ea-def5-11e6-9266-7e5a985a97ba.png)

Saturated
![skarmavbild 2017-01-20 kl 09 44 15](https://cloud.githubusercontent.com/assets/1430576/22142082/28a660e6-def5-11e6-912f-eafbf1f22fa5.png)

Not sure which you prefer. I personally think the saturated version fits your theme better.

**Comment by alex35mil** [comment]
Saturated looks cool!
